config/routes.rb
Rails.application.routes.draw do

  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end

  delete '/doses/:id', to: 'doses#destroy', as: 'delete_dose'

  root 'cocktails#index'

end

app/models/cocktail.rb
class Cocktail < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ActiveRecord::Base
  validates :description, :cocktail_id, :ingredient_id, presence: true
  validates :ingredient_id, uniqueness: { scope: :cocktail_id }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, uniqueness: true, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
     render 'new'
   end
 end

 def edit
  @cocktail = Cocktail.find(params[:id])
end

def update
  @cocktail = Cocktail.find(params[:id])
  @cocktail.update(cocktail_params)
  redirect_to cocktail_path(@cocktail)
end

def destroy
  @cocktail = Cocktail.find(params[:id])
  @cocktail.destroy
  redirect_to cocktails_path
end

private

def find_cocktail
  @cocktail = Cocktail.find(params[:id])
end

def cocktail_params
  params.require(:cocktail).permit(:name, :photo, :photo_cache)
end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])

    @ingredients = Ingredient.all - @cocktail.ingredients
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
     render 'new'
   end
 end

 def destroy
  dose = Dose.find(params[:id])
  dose.destroy
  redirect_to cocktails_path
end

private

def dose_params
  params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>

<%= f.input :photo %>
<%= f.input :photo_cache, as: :hidden %>

<%= f.submit %>
<% end %>

app/views/cocktails/edit.html.erb
<h1>Edit cocktail</h1>
<%= render 'form' %>

app/views/cocktails/index.html.erb
<div class:"container", style:"align-center">
  <h1>All cocktails:</h1>
  <% @cocktails.each do |cocktail| %>
  <ul>
    <li>
      <%= link_to cocktail.name, cocktail_path(cocktail) %>
    </li>
  </ul>
  <% end %>

  <p><%= cl_image_tag("cocktails_wqebh1.png",
    width: 400, height: 300, crop: :fill) %></p>

    <p><%= link_to "Add a new cocktail", new_cocktail_path, {class:"btn btn-primary"} %></p>
  </div>

app/views/cocktails/new.html.erb
<p>Add a new cocktail</p>
<%= render 'form' %>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %>
</h1>

<p>
  <% @cocktail.doses.each do |dose| %>
  <%= dose.description %>
  <%= dose.ingredient.name %>
  <%= link_to "Delete", delete_dose_path(dose), method: :delete %>
  <% end %>
</p>

<p><%= image_tag @cocktail.photo.url(:bright_face) %></p>

<p><%= link_to "Add an extra ingredient", new_cocktail_dose_path(@cocktail), {class:"btn btn-primary"} %></p>

<p><%= link_to "Edit", edit_cocktail_path(@cocktail), {class:"btn btn-primary"} %></p>

<p>
  <%= link_to("Delete", cocktail_path(@cocktail),
  { method: :delete, class:"btn btn-primary" }) %>
</p>

<p><%= link_to("Go back", cocktails_path, {class:"btn btn-primary"}) %></p>

app/views/doses/new.html.erb
<%= form_for([@cocktail, @dose]) do |f| %>
<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :ingredient_id %>
<%= f.collection_select(:ingredient_id, @ingredients, :id, :name) %>

<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MisterCocktail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<%= cl_image_tag("THE_IMAGE_ID_FROM_LIBRARY",
width: 400, height: 300, crop: :fill) %>